### ISSUE TITLE
js2fs not running under js-controller 3.0.14

### ISSUE THREAD

**Issue by arto5754** [iobroker-community-adapters/ioBroker.js2fs-community#18]
error:
at Object.options.ready (/opt/iobroker/node_modules/iobroker.js2fs/node_modules/soef/soef.js:1365:13)
at checkIfUpdated (/opt/iobroker/node_modules/iobroker.js2fs/node_modules/soef/soef.js:1239:20)
 [19727) TypeError: Cannot read property 'getState' of undefined
 (19727) uncaught exception: Cannot read property 'getState' of undefined

 fix did not help:

cd /opt/iobroker/node_modules/iobroker.js2fs/
sudo npm install soef
sudo iobroker restart js2fs

will fs2fs supported under  js-controller 3.0.xx?

**Comment by Apollon77** [comment]
This is a good question since JavaScript Adapter has disk mirroring included since several versions. Want eingibt that a try if it can replace this adapter for you?

**Comment by arto5754** [comment]
I didn't know that the javascript adapter could do mirroring. So the js2fs adapter is no longer necessary.
Thank you for your help!

**Comment by MubiTec** [comment]
I used this adapter until today, too. Today I updated the js-controller.
I used it to modify scripts via mobile phone. I went to the file system adapted the file and js2fs updated it in iobroker. 
Now I tried the mirror Funktion And maybe I do something wrong but if I adapt a file this script is stopped AND deleted in iobroker. Is there any other possibility?
